name: upgrade-main

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 14 * * *"

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade dependencies
        uses: p6m7g8-actions/uv-upgrade@main
        with:
          gh_token: ${{ secrets.P6_A_GH_TOKEN }}
